import type { Metadata } from "next";
import Header from "@/components/Header";
import { Geist, Geist_Mono, Bai_Jamjuree } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const baiJamjuree = Bai_Jamjuree({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-bai",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const res = await fetch(
    "https://floralwhite-echidna-890292.hostingersite.com/api/vehicles-count",
    { cache: "no-store" }
  );

  const data = await res.json();
  const totalStock = data.total || 0;
  // console.log("COUNT API:", data);
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
      <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
      />
    </head>
      <body className={`${baiJamjuree.className} min-h-full flex flex-col bg-white`}>

        {/* ✅ Global Header */}
        <div className="absolute top-0 left-0 w-full z-50">
          <Header totalStock={totalStock} />
        </div>
        
        {children}
        
          <Footer />
        </body>
    </html>
  );
}
